// The whole ICS domain layer for myco-ics: one EventStore, one relay (the
// device's embedded relay over the FIPS mesh), a per-person *participant* key
// generated in-app, and the authority model — role requests, attestations, and
// chain-of-command verification — built entirely from signed Nostr events.
//
// Myco is a dumb replication layer; it knows nothing of rank. All authority
// lives here, in the attestation graph this module interprets. See
// docs/design.md §3 (three keys), §5 (event kinds), §6 (chain verification).
import { EventStore, mapEventsToStore } from "applesauce-core";
import type { NostrEvent } from "applesauce-core/helpers";
import { RelayPool } from "applesauce-relay";
import { PrivateKeySigner } from "applesauce-signers";
import { verifyEvent } from "nostr-tools";
import { dlog } from "./debug";

// The only relay we ever talk to: the device's embedded relay, fed by the FIPS
// mesh. "People in the room" == whoever this relay is gossiping with. A
// `?relay=` query param overrides it for browser dev against a throwaway relay.
export const RELAY =
  new URLSearchParams(location.search).get("relay") ?? "ws://localhost:4869";

// --- ICS event kinds (docs/design.md §5) ------------------------------------
// Provisional POC values chosen for their Nostr classes: 9470–9475 are regular
// (stored/immutable, append-only — an incident record must not be silently
// rewritten); 39470 is addressable (replaceable-by-`d`, so a newer 202 objective
// supersedes the last). If this graduates past POC they must be registered in
// docs/reference/nostr-kinds.md so they never collide with the manifest kinds.
export const K = {
  INCIDENT: 9470, // incident announcement (IC); its own id *is* the incident id
  REQUEST: 9471, // role request (candidate); ["p", <superior>]
  ATTEST: 9472, // attestation / accept (superior); ["p", <subordinate>], role
  DENY: 9473, // denial (superior); ["e", <role-request-id>]
  OBJECTIVE: 39470, // ICS-202 objectives (addressable, d = incident id) — DOWN
  ASSIGN: 9474, // ICS-204 assignment (Operations/Division); ["p", <target>] — DOWN
  LOG: 9475, // ICS-214 activity log (any attested member) — UP
  UPDATE: 9476, // ICS-204 status/comment on an assignment; ["e", <assign-id>] — UP
  PROFILE: 0, // NIP-01 profile metadata — this responder's display name
} as const;

export const ALL_KINDS = [
  K.PROFILE,
  K.INCIDENT,
  K.REQUEST,
  K.ATTEST,
  K.DENY,
  K.OBJECTIVE,
  K.ASSIGN,
  K.LOG,
  K.UPDATE,
];

/** Assignment lifecycle (ICS-204). `open` is the implicit state before the
 *  assignee has posted any update; the rest are set by an explicit 9476. */
export type AssignStatus =
  | "open"
  | "acknowledged"
  | "in progress"
  | "blocked"
  | "complete";

export const ASSIGN_STATES: AssignStatus[] = [
  "acknowledged",
  "in progress",
  "blocked",
  "complete",
];

export const eventStore = new EventStore();
export const pool = new RelayPool();

dlog("relay url:", RELAY);

// --- participant identity (docs/design.md §3) -------------------------------
// The participant key is this *person's* identity in this incident. It is
// generated by myco-ics on first launch and is completely independent of the
// Myco device key and the nsite author key — a person's place in the chain of
// command is theirs, not their handset's. Stored in the app's own origin
// storage; no Myco secret is ever exposed to the WebView.
const SK_KEY = "myco-ics:sk";
const NAME_KEY = "myco-ics:name";

const toHex = (b: Uint8Array) =>
  Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");
const fromHex = (h: string) =>
  new Uint8Array(h.match(/.{1,2}/g)!.map((x) => parseInt(x, 16)));

function loadSigner(): PrivateKeySigner {
  const saved = localStorage.getItem(SK_KEY);
  if (saved) return new PrivateKeySigner(fromHex(saved));
  const s = new PrivateKeySigner();
  localStorage.setItem(SK_KEY, toHex(s.key));
  return s;
}

export const signer = loadSigner();
export let myPubkey = "";
signer.getPublicKey().then((pk) => {
  myPubkey = pk;
  dlog("participant pubkey:", pk.slice(0, 8));
  publishProfile(); // announce our display name once identity is ready
});

/** This responder's display name. Published as a NIP-01 kind-0 profile (so it
 *  floods and replaces cleanly) *and* echoed as an `n` tag on every event — the
 *  tag is self-contained, so a node still gets a label even if the separate
 *  profile event hasn't reached it over a lossy mesh. Auto-assigned on first
 *  launch. */
export function getName(): string {
  let name = localStorage.getItem(NAME_KEY);
  if (!name) {
    name = `Responder${100 + Math.floor(Math.random() * 900)}`;
    localStorage.setItem(NAME_KEY, name);
  }
  return name;
}

export function setName(name: string): string {
  const n = name.trim().slice(0, 32);
  if (n) {
    localStorage.setItem(NAME_KEY, n);
    publishProfile(); // replace our kind-0 so peers relabel our node
  }
  return n || getName();
}

/** Publish (replace) our NIP-01 kind-0 profile carrying the display name. */
function publishProfile(): Promise<NostrEvent> {
  return publish(K.PROFILE, JSON.stringify({ name: getName() }), []);
}

// --- read: pump the relay into the store ------------------------------------
// The device tracks every incident it sees — no filtering by incident id, since
// multiple incidents coexist on one mesh for free (docs/design.md §4). The store
// is the single source the UI derives every view from.
function startIngest() {
  pool
    .relay(RELAY)
    .subscription({ kinds: ALL_KINDS }, { reconnect: true })
    .pipe(
      mapEventsToStore(eventStore),
    )
    .subscribe({ error: (err) => dlog("ingest error:", err) });
}
startIngest();

/** Reactive timeline of *all* ICS events — the UI recomputes derived views
 *  (incidents, org chart, messages) from this on every add. */
export function icsTimeline$() {
  return eventStore.timeline({ kinds: ALL_KINDS });
}

// --- tag helpers ------------------------------------------------------------
export const tag = (e: NostrEvent, name: string): string | undefined =>
  e.tags.find((t) => t[0] === name)?.[1];

/** every value of a repeated tag (e.g. all `e` tags). */
const tagAll = (e: NostrEvent, name: string): string[] =>
  e.tags.filter((t) => t[0] === name).map((t) => t[1]);

const refsIncident = (e: NostrEvent, incidentId: string) =>
  tagAll(e, "e").includes(incidentId);

const pTarget = (e: NostrEvent): string | undefined => tag(e, "p");

/** the `e` tag marked as a `reply` (or, failing markers, the 2nd `e`). */
const replyTo = (e: NostrEvent): string | undefined => {
  const reply = e.tags.find((t) => t[0] === "e" && t[3] === "reply");
  if (reply) return reply[1];
  const es = tagAll(e, "e");
  return es.length > 1 ? es[1] : undefined;
};

/** Resolve a pubkey to a display name: prefer the latest kind-0 profile, then
 *  fall back to the latest `n` tag carried on any event, then a short pubkey. */
export function nameOf(events: NostrEvent[], pubkey: string): string {
  let profile: NostrEvent | undefined;
  let tagged: NostrEvent | undefined;
  for (const e of events) {
    if (e.pubkey !== pubkey) continue;
    if (e.kind === K.PROFILE && (!profile || e.created_at > profile.created_at)) {
      profile = e;
    } else if (tag(e, "n") && (!tagged || e.created_at > tagged.created_at)) {
      tagged = e;
    }
  }
  if (profile) {
    try {
      const n = (JSON.parse(profile.content) as { name?: string }).name;
      if (n) return n;
    } catch {
      // malformed profile → fall through to the tag
    }
  }
  return tagged ? tag(tagged, "n")! : pubkey.slice(0, 8);
}

const now = () => Math.floor(Date.now() / 1000);

async function publish(
  kind: number,
  content: string,
  tags: string[][],
): Promise<NostrEvent> {
  const signed = await signer.signEvent({
    kind,
    created_at: now(),
    content,
    tags: [...tags, ["n", getName()], ["client", "myco-ics"]],
  });
  eventStore.add(signed); // local echo first, then hand to the relay → mesh
  dlog("publish:", `k${kind}`, signed.id.slice(0, 8));
  try {
    await pool.relay(RELAY).publish(signed);
  } catch (e) {
    dlog("publish error:", e);
    throw e;
  }
  return signed;
}

/**
 * Re-flood every event *I* authored back to the relay, so a peer who joined
 * late (or was out of range) picks up my whole contribution to the graph — the
 * mesh only lazily backfills history, so a manual re-announce closes the gap
 * (docs/design.md §9 step 3). Re-publishing is safe: the relay/mesh dedup on
 * event id, so this can't duplicate or fork anything. Returns the count sent.
 */
export async function republishMine(): Promise<number> {
  const mine = eventStore.getByFilters({ authors: [myPubkey], kinds: ALL_KINDS });
  dlog("republish: re-flooding", mine.length, "of my events");
  let sent = 0;
  for (const ev of mine) {
    try {
      await pool.relay(RELAY).publish(ev);
      sent++;
    } catch (e) {
      dlog("republish error:", ev.id.slice(0, 8), e);
    }
  }
  dlog("republish: done,", sent, "sent");
  return sent;
}

// --- write: the ICS actions (docs/design.md §8) -----------------------------

/** 8.1 — declare an incident. The returned event's id *is* the incident id, and
 *  its author (me) is the root of that incident's chain of command. */
export function startIncident(name: string): Promise<NostrEvent> {
  return publish(K.INCIDENT, name.trim(), []);
}

/** 8.2 — request a role under a chosen superior (or under the IC directly). */
export function requestRole(
  incidentId: string,
  superior: string,
  role: string,
): Promise<NostrEvent> {
  return publish(K.REQUEST, "", [
    ["e", incidentId],
    ["p", superior],
    ["role", role],
  ]);
}

/** 8.3 — accept a request: publish the attestation that puts the candidate in
 *  the chain under me. This is the trust primitive (docs/design.md §3). */
export function accept(request: NostrEvent): Promise<NostrEvent> {
  const incidentId = tagAll(request, "e")[0];
  return publish(K.ATTEST, "", [
    ["e", incidentId],
    ["p", request.pubkey],
    ["role", tag(request, "role") ?? "Member"],
    ["e", request.id, "", "reply"],
  ]);
}

/** 8.3 — deny a request. */
export function deny(request: NostrEvent): Promise<NostrEvent> {
  const incidentId = tagAll(request, "e")[0];
  return publish(K.DENY, "", [
    ["e", incidentId],
    ["p", request.pubkey],
    ["e", request.id, "", "reply"],
  ]);
}

/** 8.5 down — ICS-202 objectives (addressable; a newer 202 supersedes). */
export function publishObjective(
  incidentId: string,
  text: string,
): Promise<NostrEvent> {
  return publish(K.OBJECTIVE, text.trim(), [
    ["d", incidentId],
    ["e", incidentId],
  ]);
}

/** 8.5 down — ICS-204 assignment addressed at a division/person. */
export function publishAssignment(
  incidentId: string,
  target: string,
  text: string,
): Promise<NostrEvent> {
  return publish(K.ASSIGN, text.trim(), [
    ["e", incidentId],
    ["p", target],
  ]);
}

/** 8.5 up — ICS-214 activity-log entry authored at the edge. */
export function publishLog(
  incidentId: string,
  text: string,
): Promise<NostrEvent> {
  return publish(K.LOG, text.trim(), [["e", incidentId]]);
}

/** Post an update on an assignment — a status change, a comment, or both. The
 *  assignee acknowledges, reports progress, or marks complete; the issuing
 *  leader can chime in too. Threads under the assignment via a reply e-tag, and
 *  flows *up* the chain like a 214 log entry. */
export function publishAssignmentUpdate(
  incidentId: string,
  assignmentId: string,
  status: AssignStatus | null,
  comment: string,
): Promise<NostrEvent> {
  const tags: string[][] = [
    ["e", incidentId],
    ["e", assignmentId, "", "reply"],
  ];
  if (status) tags.push(["status", status]);
  return publish(K.UPDATE, comment.trim(), tags);
}

// --- derive: incidents ------------------------------------------------------
export interface Incident {
  id: string;
  name: string;
  ic: string; // IC participant pubkey (root of trust)
  created_at: number;
}

export function incidents(events: NostrEvent[]): Incident[] {
  return events
    .filter((e) => e.kind === K.INCIDENT)
    .map((e) => ({
      id: e.id,
      name: e.content || "(unnamed incident)",
      ic: e.pubkey,
      created_at: e.created_at,
    }))
    .sort((a, b) => b.created_at - a.created_at);
}

const incidentEvent = (events: NostrEvent[], id: string) =>
  events.find((e) => e.kind === K.INCIDENT && e.id === id);

// --- derive: attestation-chain verification (docs/design.md §6) -------------
export type Status = "verified" | "pending" | "denied" | "broken";

export interface PathLink {
  pubkey: string;
  role: string;
}

/** The 9472 attestation naming `pubkey` as a subordinate in this incident,
 *  signature-checked. The subordinate cannot forge it — they don't hold the
 *  superior's key — which is the self-authenticating property the whole model
 *  rests on. */
function attestationFor(
  events: NostrEvent[],
  incidentId: string,
  pubkey: string,
): NostrEvent | undefined {
  return events.find(
    (e) =>
      e.kind === K.ATTEST &&
      refsIncident(e, incidentId) &&
      pTarget(e) === pubkey &&
      verifyEvent(e),
  );
}

/**
 * Verify that `pubkey` holds a role in `incidentId`, returning the full
 * verification path up to the IC (docs/design.md §6):
 *   1. find the signed 9472 naming pubkey; its author Q is the claimed superior.
 *   2. if Q is the IC (authored the 9470 whose id is the incident) → verified.
 *   3. otherwise recurse on Q.
 *   4. a missing/bad attestation or a cycle → broken; no attestation at the
 *      queried node itself (only a request outstanding) → pending.
 */
export function verify(
  events: NostrEvent[],
  incidentId: string,
  pubkey: string,
): { status: Status; path: PathLink[] } {
  const ic = incidentEvent(events, incidentId)?.pubkey;
  if (!ic) return { status: "broken", path: [] };

  const path: PathLink[] = [];
  const seen = new Set<string>();
  let cur = pubkey;

  while (true) {
    if (cur === ic) {
      path.push({ pubkey: ic, role: "Incident Commander" });
      return { status: "verified", path };
    }
    if (seen.has(cur)) return { status: "broken", path }; // cycle
    seen.add(cur);

    const att = attestationFor(events, incidentId, cur);
    if (!att) {
      // No attestation for the *queried* node → it has only requested (pending).
      // A break higher up the chain → broken.
      return { status: path.length === 0 ? "pending" : "broken", path };
    }
    path.push({ pubkey: cur, role: tag(att, "role") ?? "Member" });
    cur = att.pubkey; // ascend to the attester (superior)
  }
}

// --- derive: the org chart (docs/design.md §8.4) ----------------------------
export interface OrgNode {
  pubkey: string;
  name: string;
  role: string;
  status: Status;
  parent: string | null; // attester (verified/broken) or requested superior (pending)
  requestId?: string; // set for pending nodes, so a superior can accept/deny
}

/**
 * Build the incident org chart from the local event graph alone — no server, no
 * network, fully offline. Every participant that has either been attested or has
 * an outstanding request becomes a node, tagged with its verification status.
 */
export function orgChart(
  events: NostrEvent[],
  incidentId: string,
): { ic: string | null; nodes: OrgNode[] } {
  const incident = incidentEvent(events, incidentId);
  if (!incident) return { ic: null, nodes: [] };
  const ic = incident.pubkey;

  const inInc = events.filter((e) => refsIncident(e, incidentId));
  const requests = inInc.filter((e) => e.kind === K.REQUEST);
  const attests = inInc.filter((e) => e.kind === K.ATTEST && verifyEvent(e));
  const denials = inInc.filter((e) => e.kind === K.DENY);

  // Requests that a superior has already answered (accepted or denied).
  const answered = new Set<string>();
  for (const a of attests) {
    const r = replyTo(a);
    if (r) answered.add(r);
  }
  const deniedReq = new Set<string>();
  for (const d of denials) {
    const r = replyTo(d);
    if (r) {
      answered.add(r);
      deniedReq.add(r);
    }
  }

  const nodes = new Map<string, OrgNode>();

  // The IC is the axiomatic root.
  nodes.set(ic, {
    pubkey: ic,
    name: nameOf(events, ic),
    role: "Incident Commander",
    status: "verified",
    parent: null,
  });

  // Everyone named in an attestation: resolve their real status via §6.
  for (const a of attests) {
    const sub = pTarget(a);
    if (!sub || sub === ic) continue;
    const { status } = verify(events, incidentId, sub);
    nodes.set(sub, {
      pubkey: sub,
      name: nameOf(events, sub),
      role: tag(a, "role") ?? "Member",
      status,
      parent: a.pubkey,
    });
  }

  // Outstanding / denied requests that never became attestations → show pending
  // or denied under the *requested* superior, so a leader can act on them.
  for (const r of requests) {
    const sub = r.pubkey;
    if (sub === ic || nodes.has(sub)) continue; // already attested → skip
    if (answered.has(r.id) && !deniedReq.has(r.id)) continue; // accepted elsewhere
    nodes.set(sub, {
      pubkey: sub,
      name: nameOf(events, sub),
      role: tag(r, "role") ?? "Member",
      status: deniedReq.has(r.id) ? "denied" : "pending",
      parent: pTarget(r) ?? ic,
      requestId: r.id,
    });
  }

  return { ic, nodes: [...nodes.values()] };
}

/** Requests addressed to me that I have not yet accepted or denied — the
 *  leader accept/deny gate (docs/design.md §8.3), this app's only admission
 *  control. */
export function pendingForMe(
  events: NostrEvent[],
  incidentId: string,
  me: string,
): NostrEvent[] {
  const inInc = events.filter((e) => refsIncident(e, incidentId));
  const answered = new Set<string>();
  for (const e of inInc) {
    if (e.kind === K.ATTEST || e.kind === K.DENY) {
      const r = replyTo(e);
      if (r) answered.add(r);
    }
  }
  return inInc
    .filter(
      (e) =>
        e.kind === K.REQUEST &&
        pTarget(e) === me &&
        !answered.has(e.id),
    )
    .sort((a, b) => b.created_at - a.created_at);
}

// --- derive: messages / forms (docs/design.md §8.5) -------------------------
export function objective(
  events: NostrEvent[],
  incidentId: string,
): NostrEvent | undefined {
  return events
    .filter((e) => e.kind === K.OBJECTIVE && tag(e, "d") === incidentId)
    .sort((a, b) => b.created_at - a.created_at)[0];
}

export function assignments(
  events: NostrEvent[],
  incidentId: string,
): NostrEvent[] {
  return events
    .filter((e) => e.kind === K.ASSIGN && refsIncident(e, incidentId))
    .sort((a, b) => b.created_at - a.created_at);
}

export interface AssignThread {
  status: AssignStatus; // latest status set on the assignment (else "open")
  updates: NostrEvent[]; // every 9476 replying to it, oldest first
}

/** The status + comment thread for one assignment (its 9476 replies). The
 *  latest update that carries a `status` tag wins; comments accumulate. */
export function assignmentThread(
  events: NostrEvent[],
  assignmentId: string,
): AssignThread {
  const updates = events
    .filter((e) => e.kind === K.UPDATE && replyTo(e) === assignmentId)
    .sort((a, b) => a.created_at - b.created_at);
  let status: AssignStatus = "open";
  for (const u of updates) {
    const s = tag(u, "status") as AssignStatus | undefined;
    if (s) status = s;
  }
  return { status, updates };
}

export function activityLog(
  events: NostrEvent[],
  incidentId: string,
): NostrEvent[] {
  return events
    .filter((e) => e.kind === K.LOG && refsIncident(e, incidentId))
    .sort((a, b) => b.created_at - a.created_at);
}
